---
name: Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2, 3.3]
    env:
      PGHOST: localhost
      PGUSER: administrate
      PGPASSWORD: administrate
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: administrate
          POSTGRES_DB: administrate_test
          POSTGRES_PASSWORD: administrate
        ports:
           - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Set up JS
        uses: actions/setup-node@v4
        with:
          cache: yarn
      - name: Install Ruby dependencies
        run: bundle install
      - name: Install Appraisal dependencies for Rails 6.0
        run: BUNDLE_GEMFILE=gemfiles/rails60.gemfile bundle install
        if: ${{ matrix.ruby <= '3.0' }}
      - name: Install Appraisal dependencies for Rails 6.1
        run: BUNDLE_GEMFILE=gemfiles/rails61.gemfile bundle install
      - name: Install Appraisal dependencies for Rails 7.0
        run: BUNDLE_GEMFILE=gemfiles/rails70.gemfile bundle install
      - name: Install Appraisal dependencies for Rails 8.0
        run: BUNDLE_GEMFILE=gemfiles/rails80.gemfile bundle install
        if: ${{ matrix.ruby >= '3.2' }}
      - name: Install JS dependencies
        run: yarn install
      - name: Setup the environment
        run: cp .sample.env .env
      - run: cp spec/example_app/config/database.yml.sample spec/example_app/config/database.yml
      - name: Setup the database
        run: bundle exec rake db:setup
      - name: Build assets
        run: yarn run build && yarn run build:css
      - name: Run tests
        run: bundle exec rspec
        if: ${{ matrix.ruby >= '3.2' }}
      - name: Appraise Rails 6.0
        run: bundle exec appraisal rails60 rspec
        if: ${{ matrix.ruby <= '3.0' }}
      - name: Appraise Rails 6.1
        run: bundle exec appraisal rails61 rspec
      - name: Appraisal Rails 7.0
        run: bundle exec appraisal rails70 rspec
      - name: Appraisal Rails 8.0
        run: bundle exec appraisal rails80 rspec
        if: ${{ matrix.ruby >= '3.2' }}
